### ISSUE TITLE
Support InlineFragment fields?

### ISSUE THREAD

**Issue by mattkrick** [kadirahq/graphql-utils-js#1]
For the getFields, might be useful to include `InlineFragment`
See: https://facebook.github.io/graphql/#sec-Inline-Fragments
Or the whole function: https://github.com/graphql/graphql-js/issues/96#issuecomment-138145869

(Might be nice to include this in learngraphql.com, too!)

**Comment by arunoda** [comment]
Thanks. Yeah. We should do it too.

**Comment by arunoda** [comment]
If you have some time for that, send me a PR.

**Comment by mattkrick** [comment]
Sure, you thinking about merging the 2 functions or wanna keep em separate?
